[build]
  base = "frontend"
  publish = "dist"
  command = "npm run build"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "DYNAMIC_ENVIRONMENT_ID,CHAIN_ID,MOCK"
  PNPM_FLAGS = "--no-frozen-lockfile"
